language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

before_install:
  - export DJANGO_SETTINGS_MODULE=dbtemplates.test_settings
install:
  - pip install -e .
  - pip install -r requirements/tests.txt Django==$DJANGO
before_script:
  - flake8 dbtemplates --ignore=E501
script:
  - coverage run --branch --source=dbtemplates `which django-admin.py` test dbtemplates
  - coverage report --omit="dbtemplates/test*,dbtemplates/migrations*"
env:
  - DJANGO=1.4.5
  - DJANGO=1.5.1
  - DJANGO=1.6.4
matrix:
    exclude:
        - python: "3.3"
          env: DJANGO=1.5.1
        - python: "3.3"
          env: DJANGO=1.4.5
        - python: "3.3"
          env: DJANGO=1.3.7
        - python: "3.4"
          env: DJANGO=1.5.1
        - python: "3.4"
          env: DJANGO=1.4.5
        - python: "3.4"
          env: DJANGO=1.3.7

branches:
  only:
    - develop
